'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'

export default function LoginPage() {
  const [submitted, setSubmitted] = useState(false)
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true) }
  return <main className="auth-shell"><div className="auth-grid"><section className="auth-brand"><Link href="/" className="auth-back">← AETHER TERMINAL</Link><div className="auth-mark">A</div><div className="eyebrow"><span className="diamond">◆</span> MARKET INTELLIGENCE</div><h1>Decisions,<br /><em>with evidence.</em></h1><p>Access your market workspace, verified signals, and reproducible strategy history.</p><div className="auth-status"><span className="live-dot" /> SYSTEMS OPERATIONAL <span>ENCRYPTED SESSION</span></div></section><section className="auth-card"><div className="auth-card-head"><div><span className="overline">ONE-SECOND ACCESS</span><h2>Welcome back.</h2><p className="auth-subtitle">개인정보 입력 없이 안전하게 시작하세요.</p></div><span className="status-tag">SECURE</span></div><div className="social-grid social-grid-wide"><button className="social-button" type="button"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/naver/default.svg" alt="Naver" /> NAVER <span>↗</span></button><button className="social-button" type="button"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/kakao/default.svg" alt="Kakao" /> KAKAO <span>↗</span></button><button className="social-button" type="button"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/google/default.svg" alt="Google" /> GOOGLE <span>↗</span></button><button className="social-button" type="button"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/apple/default.svg" alt="Apple" /> APPLE <span>↗</span></button></div><button className="wallet-button" type="button"><span className="wallet-mark">◇</span> CONNECT METAMASK <small>ANONYMOUS WEB3 ACCESS</small><span>↗</span></button><form onSubmit={submit}><label>Email address<input type="email" required placeholder="you@company.com" /></label><label>Password<input type="password" required placeholder="Enter your password" /></label><div className="auth-options"><label className="check"><input type="checkbox" /> Remember me</label><button type="button" className="auth-link">Forgot password?</button></div><button className="primary-button auth-submit" type="submit">{submitted ? 'SESSION READY' : 'SIGN IN'} <span>↗</span></button></form><div className="auth-divider"><span>ACCESS POLICY</span></div><p className="privacy-note">본 서비스는 개인정보 최소수집 원칙을 준수하며, 비밀번호나 민감정보를 절대 저장하지 않습니다.</p></section></div></main>
}
