'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'

export default function SignupPage() {
  const [submitted, setSubmitted] = useState(false)
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true) }
  return <main className="auth-shell"><div className="auth-grid"><section className="auth-brand"><Link href="/" className="auth-back">← AETHER TERMINAL</Link><div className="auth-mark">A</div><div className="eyebrow"><span className="diamond">◆</span> PUBLIC MARKET INTELLIGENCE</div><h1>Build your<br /><em>edge.</em></h1><p>Join a transparent workspace for signals, backtests, and decisions grounded in evidence.</p><div className="auth-status"><span className="live-dot" /> FREE WORKSPACE <span>NO CARD REQUIRED</span></div></section><section className="auth-card"><div className="auth-card-head"><div><span className="overline">NEW ACCOUNT</span><h2>Start with signal.</h2></div><span className="status-tag">OPEN</span></div><div className="social-grid"><button className="social-button" type="button"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/google/default.svg" alt="Google" /> GOOGLE <span>↗</span></button><button className="social-button" type="button"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/apple/default.svg" alt="Apple" /> APPLE <span>↗</span></button><button className="social-button" type="button"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/naver/default.svg" alt="Naver" /> NAVER <span>↗</span></button></div><div className="auth-divider"><span>OR USE EMAIL</span></div><form onSubmit={submit}><label>Full name<input type="text" required placeholder="Your name" /></label><label>Work email<input type="email" required placeholder="you@company.com" /></label><label>Password<input type="password" required minLength={8} placeholder="8 characters minimum" /></label><label className="check terms"><input type="checkbox" required /> I agree to the terms and privacy policy</label><button className="primary-button auth-submit" type="submit">{submitted ? 'WORKSPACE CREATED' : 'CREATE WORKSPACE'} <span>↗</span></button></form><p className="auth-footer">Already have an account? <Link href="/login">Sign in</Link></p></section></div></main>
}
